### PR TITLE
Data update and download script

### PR DESCRIPTION
**Pull request by touzoku**
* Add Japanese entries to geonames and OSM
* Fix Indonesia
* Fix Chinese entries
* Rename Swaziland to Eswatini and Macedonia to North Macedonia
* Update existing names from wikipedia
* Add Japanese, Hindi, Portugues, Italian, and Hebrew to iso3166-2.json from Wikipedia

### CODE REVIEW

**Comment by touzoku** [comment]
@theKashey I have updated the data files only. I did not run prepublish.js as it produces a lot of files, and I am not quite sure I ran it correctly. If you could produce countryNames and update the npm package, it would be greatly appreciated!

**Comment by theKashey** [comment]
👍

**Comment by theKashey** [comment]
Marat - how did you do that?
I mean - I've generated all the files from the database, which become a bit obsolete by the time, and I've got some problems keeping up to date... But how did you do it?

**Comment by touzoku** [comment]
@theKashey I can commit my scripts under ./bin, if you'd like!

**Comment by theKashey** [comment]
It's more about - I can't commit my scripts as long as geonames database is a few gigabytes, and OSM is a few dozen gigabytes.
But if your ones are not coupled to a local DB - please share them.

**Comment by touzoku** [comment]
My scripts just crawl www.geonames.org, www.openstreetmap.org, and wikimedia API based on your IDs. The scripts can't tell whether your IDs are accurate or not, however.

**Comment by touzoku** [comment]
Btw, my quick wikipedia check for the ISO-3611-1 showed that the dataset is missing the following countries:
AW AX BL BV CC CW CX EH HM MF NC NF PF SJ SX TL

If you could commit them somehow, it would be greatly appreciated!

**Comment by theKashey** [comment]
Yeah, there is a issue about it https://github.com/esosedi/3166/issues/16. I'll try to add mission ones. At least 3611-1, not -2.

> The scripts can't tell whether your IDs are accurate or not, however.
"initial" scripts were matching different dataset, but they all always containing some mistakes.

**Comment by touzoku** [comment]
* Added multiple languages to names_osm and geonames as well (besides main file generated from Wikipedia).

Also added the download script (please ignore the other PR). Basically, you can reproduce this PR deterministically by running ./bin/download.js. The only manual change I made was renaming "Виргинские Острова" to "Британские Виргинские Острова" and "Американские Виргинские Острова" correspondingly (the parentheses removal regexp removes it from wikipedia page names)

**Comment by theKashey** [comment]
Released in 2.3.5

**Pull request merged**
